[package]
name = "ai-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
ollama-rs = { version = "0.3.1", features = ["stream"] }
tokio = "1.45.1"
rustyline = "12.0.0"
ansi_term = "0.12.1"
tokio-stream = "0.1"

[dev-dependencies]
assert_cmd = "2.0"
